services:
  - type: web
    name: studio99-web
    env: docker
    region: ohio
    plan: free # Change to starter/pro for production
    healthCheckPath: /up
    envVars:
      - key: PORT
        value: 8000
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://studio99.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: studio99-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: studio99-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: studio99-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: studio99-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: studio99-db
          property: password

databases:
  - name: studio99-db
    databaseName: studio99
    user: studio99_user
    region: ohio
    plan: free # Change to starter/pro for production
